const paletaColoresDigitama = ["Rojo", "Amarillo", "Azul", "Naranja", "Verde", "Violeta", "Turquesa", "Blanco", "Negro", "Gris", "Marrón", 
    "Magenta", "Celeste", "Rosa", "Ocre", "Crema"];

const bancoDatos = {
    "digitama": {
        "0": paletaColoresDigitama,
        "1": ["Liso", "Militar", "Electricidad", "Anillos horizontales", "Lunares", "Círculos", 
            "Manchas", "Anillos diagonales", "Rayas onduladas", "Atigrado horizontal", "Patrón tipo grietas", 
            "Llamas", "Hojas", "Remaches", "Estrellas", "Espirales", "Triángulos", "Aros", "Ondas", 
            "Flores", "Atigrado diagonal", "Manchas leopardo", "Ondulaciones", "Escamas", 
            "Símbolo Murciélago (ejemplo: Devimon)", "Símbolo Digital Hazard (Ejemplo: Megidramon)", "Símbolo Zero Unit (Ejemplo: Culumon)", "Símbolo coraje", 
            "Símbolo Amistad", "Símbolo esperanza", "Símbolo bondad", "Símbolo conocimiento", 
            "Símbolo luz", "Circuito", "Símbolo Bestia (Ejemplo: Armadillomon)", "Símbolo amor", 
            "Símbolo pureza", "Símbolo sinceridad", "Símbolo Milagros", "Símbolo Bondad", "Símbolo Destino"],

        "2": ["Rojo", "Amarillo", "Azul", "Naranja", "Verde", "Violeta", "Turquesa", "Blanco", "Negro", "Gris", "Marrón", "Magenta", "Celeste", "Rosa", "Ocre", "Crema"],

        "3": ["Espinas", "Escamas", "Placa Hexagonos", "Nada", "Cuernos", "Nada", "Sombra interna", "Nada", "Alas ángel", "Alas demonio", "Holy ring", "Digicode",
            "Nada","Alas Dragón"],

        "4": ["Nada", "Color más Saturado", "Color menos Saturado", "Resplandor", "Aura color patrón", "Aura Color Base", "Pixel", "Boxels", "wireframe 3D", "Nada",
            "Digitama en eclosión"]
    },

    "digimon": {
        "0": ["Baby I", "Baby II", "Child", "Adult", "Perfect", "Ultimate"],
 "listasMaestras": {
            "Baby": ["Algomon (Baby I)", "Bombmon", "Bommon", "Botamon", "Bubbmon", "Chibickmon", "Chicomon", "Choromon", "Cocomon", "Cotsucomon", "Curimon", "Dodomon",
            "Dokimon", "Fufumon", "Fukamon", "Fusamon", "Jyarimon", "Keemon", "Kekomon", "Ketomon", "Kuramon", "Leafmon", "Mokumon", "Nyokimon",
            "Pafumon", "Paomon", "Peti Meramon", "Petitmon", "Pipimon", "Pitchmon", "Popomon", "Poyomon", "Punimon", "Pupumon", "Pururumon", "Pusumon", "Puttimon",
            "Puwamon", "Puyomon", "Pyonmon", "Relemon", "Sakumon", "Sunamon", "Tomorimon", "Torikara Ballmon", "Tsubumon", "Yolkmon", "Yukimi Botamon", "Yuramon", "Zerimon",
            "Zurumon", "Algomon (Baby II)", "Arkadimon Baby", "Babydmon", "Bibimon", "Bosamon", "Bowmon", "Budmon", "Caprimon", "Chapmon", "Chibimon", "Chicchimon",
            "Chocomon", "Cupimon", "Dorimon", "Fluffymon", "Frimon", "Gaossmon", "Gigimon", "Goromon", "Gummymon", "Gurimon", "Hiyarimon", "Hopmon", "Kakkinmon",
            "Kekkomon", "Kodokugumon Baby", "Koromon", "Kozenimon", "Kyaromon", "Kyokyomon", "Meicoomon's Unnamed Baby Form", "Minomon", "Missimon", "Mochimon",
            "Mococomon", "Monimon", "Moonmon", "Negamon", "Nyaromon", "Onibimon", "Otamamon", "Pagumon", "Peti Meramon", "Pickmon", "Pinamon", "Pokomon", "Poromon",
            "Pukamon", "Puroromon", "Pusurimon", "Puyoyomon", "Pyocomon", "Sakuttomon", "Sunmon", "Tanemon", "Tokomon", "Tokomon (X-Antibody)", "Torikara Ballmon",
            "Tsumemon", "Tunomon", "Upamon", "Vitium Baby", "Wanyamon", "Xiaomon", "Yarmon"],

            "Child": ["Agnimon", "Agumon", "Agumon (2006 Anime Version)", "Agumon (Black)", "Agumon (Black) (2006 Anime Version)", "Agumon (Black) (X-Antibody)", 
                    "Agumon (X-Antibody)", "Agumon Hakase", "Algomon (Child)", "Allomon", "Alraumon", "Angoramon", "Arkadimon Child", "Armadimon", "Bacomon", "Bakumon", 
                    "Betamon", "Betamon (X-Antibody)", "Black Guilmon", "Black Tailmon", "Blucomon", "Bokomon", "Bun", "Burgamon", "Bushi Agumon", "Candmon", "Cardmon C1",
                    "Cardmon C2", "Chikurimon", "Chiropmon", "Clear Agumon", "Commandramon", "Coronamon", "Culumon", "Cutemon", "Dark Lizamon", "Deadly Axemon", "Dokunemon",
                    "Dondokomon", "DORUmon", "Dracomon", "Dracomon (X-Antibody)", "Dracumon", "Drimogemon", "Ebi Burgamon", "Ekakimon", "Elecmon", "Elecmon (Violet)",
                    "Elizamon", "Espimon", "Falcomon", "Falcomon (2006 Anime Version)", "Fladramon", "Flare Lizamon", "Floramon", "Flybeemon", "Fujamon", "Funbeemon",
                    "Gabumon", "Gabumon (Black)", "Gabumon (X-Antibody)", "Gammamon", "Ganimon", "Ganimon (X-Antibody)", "Gaomon", "Gaossmon", "Gargomon", "Gasamon",
                    "Gazimon", "Gazimon (X-Antibody)", "Gekkomon", "Gemmon", "Ghostmon", "Gizamon", "Goburimon", "Gomamon", "Gomamon (X-Antibody)", "Gottsumon",
                    "Gottsumon (X-Antibody)", "Greymon (2010 Anime Version)", "Guilmon", "Guilmon (X-Antibody)", "Gumdramon", "Hackmon", "Hagurumon", "Hagurumon (X-Antibody)",
                    "Hanimon", "Hawkmon", "Herissmon", "Holsmon", "Hyemon", "Hyokomon", "Icemon", "Iguneetmon", "Impmon", "Impmon (X-Antibody)", "Insekimon", "Jazamon",
                    "Jellymon", "Junkmon", "Kakamon", "Kamemon", "Keramon", "Keramon (X-Antibody)", "Kodokugumon Baby", "Kodokugumon Child", "Koemon", "Kokabuterimon",
                    "Kokuwamon", "Kokuwamon (X-Antibody)", "Kongoumon", "Kotemon", "Kudamon", "Kudamon (2006 Anime Version)", "Kunemon", "Labramon", "Lalamon", "Lighdramon",
                    "Liollmon", "Loogamon", "Lopmon", "Lopmon (X-Antibody)", "Lucemon", "Ludomon", "Lunamon", "Luxmon", "Maquinamon", "Metabee", "Minidekachimon",
                    "Modoki Betamon", "Monitamon", "Monodramon", "Morphomon", "Muchomon", "Mushmon", "Neamon", "Nise Agumon Hakase", "Otamamon", "Otamamon (Red)",
                    "Otamamon (X-Antibody)", "Palmon", "Palmon (X-Antibody)", "Patamon", "Pawn Chessmon (Black)", "Pawn Chessmon (White)", "Pegasmon", "Penmon", "Peti Meramon",
                    "Petit Mamon", "Phascomon", "Pico Devimon", "Pillomon", "Piyomon", "Plotmon", "Plotmon (X-Antibody)", "Pomumon", "Pristimon", "Proto Gizmon", "Psychemon",
                    "Pteromon", "Pulsemon", "Renamon", "Renamon (X-Antibody)", "Rinkmon", "Rokusho", "Ryudamon", "Sand Yanmamon", "Sangomon", "Santa Agumon", "Sepikmon",
                    "Shakomon", "Shakomon (X-Antibody)", "Shamamon", "Shoemon", "Shoujishou", "Shoutmon", "Shoutmon (King Ver.)", "Shoutmon Black", "Shoutmon Star Wheel",
                    "Shoutmon  Star Sword", "Shurimon", "Sistermon Blanc", "Sistermon Blanc (Awake)", "Skull Knightmon", "Snow Goburimon", "Solarmon", "Soundbirdmon",
                    "Spadamon", "Sparrowmon", "Starmons", "Strabimon", "Sunarizamon", "Swimmon", "Tailmon", "Takinmon", "Tentomon", "Terriermon", "Terriermon (X-Antibody)",
                    "Terriermon Assistant", "Tinkermon", "Tinpet", "Tocanmon", "Toy Agumon", "Toy Agumon (Black)", "Tukaimon", "Tyumon", "Tyutyumon", "Ukkomon", "Vmon",
                    "Vorvomon", "Wankomon", "White Lopmon", "Wormmon", "Yaksamon", "Yanmamon", "Yuki Agumon", "Yuki Agumon 2006", "Zenimon", "Zubamon", "Aequcedramon",
                    "Ganvivormon", "Hubmon", "Madomon", "Pyontomon", "Rurimon"],

            "Adult": ["Aegiomon", "Airdramon", "Akatorimon", "Algomon (Adult)", "Allomon", "Allomon (X-Antibody)", "Angemon", "Ankylomon", "Aquilamon", "Arbormon", "Archelomon",
                      "Arkadimon Adult", "Arma Lizamon", "Arresterdramon", "Atamadekachimon", "Baboongamon", "Bakemon", "Ballistamon", "Baluchimon", "Bao Hackmon", "Baromon",
                      "Battle Armament Trailmon", "Betel Gammamon", "Bio Coatlmon", "Bio Stegomon", "Bio Thunderbirmon", "Birdramon", "Bitmon", "Black Galgomon",
                      "Black Gaogamon", "Black Growmon", "Black Tailmon", "Black Tailmon Uver.", "Blade Kuwagamon", "Blimpmon", "Blitzmon", "Blue Meramon", "Boarmon",
                      "Bomber Nanimon", "Boogiemon", "Bulkmon", "Bullmon", "Buraimon", "Burgamon Adult", "Butterflamon", "Cardmon U1", "Cardmon U2", "Centalmon", "Chackmon",
                      "Chamblemon", "Chamelemon", "Chrysalimon", "Citramon", "Clockmon", "Coatlmon", "Cockatrimon", "Coelamon", "Coredramon (Blue)", "Coredramon (Green)",
                      "Cougarmon", "Cyclomon", "Damemon", "Darcmon", "Dark Knightmon", "Dark Lizamon", "Dark Maildramon", "Dark Tyranomon", "Dark Tyranomon (X-Antibody)",
                      "Deadly Axemon", "Death-X-DORUgamon", "Deckerdramon", "Deltamon", "Depthmon", "Devidramon", "Devimon", "Diatrymon", "Digmon", "Dimetromon", "Dinohumon",
                      "Dobermon", "Dobermon (X-Antibody)", "Dogmon", "Dokugumon", "Don Shoutmon", "DORUgamon", "Dorulumon", "Drimogemon", "Duskmon", "Earthdramon", "Ebidramon",
                      "Elephamon", "Eosmon (Adult)", "Evilmon", "Exermon", "Eyesmon", "Eyesmon: Scatter Mode", "Fairimon", "Fangmon", "Filmon", "Firamon", "Fla Wizarmon",
                      "Fladramon", "Flare Lizamon", "Flybeemon", "Flymon", "Forgebeemon", "Frogmon", "Fugamon", "Galemon", "Galgomon", "Ganemon", "Gaogamon", "Gargomon",
                      "Garummon", "Garurumon", "Garurumon (Black)", "Garurumon (X-Antibody)", "Gawappamon", "Gekomon", "Geo Greymon", "Geremon", "Gesomon", "Gesomon (X-Antibody)",
                      "Gigantic Numemon", "Ginkakumon", "Ginkakumon Promote", "Ginryumon", "Gizmon: AT", "Gladimon", "Goatmon", "Gokimon", "Gold Numemon", "Gold V-dramon",
                      "Golemon", "Golemon (PlayStation)", "Gorimon", "Gottsumon", "Great King Scumon", "Greymon", "Greymon (2010 Anime Version)", "Greymon (Blue)", 
                      "Greymon (Blue) (X-Antibody)", "Greymon (X-Antibody)", "Grimmon", "Grottemon", "Growmon", "Growmon (Orange)", "Growmon (X-Antibody)", "Gryzmon",
                      "Guardromon", "Guardromon (Gold)", "Gulus Gammamon", "Gururumon", "Hakubamon", "Hanumon", "Harpymon", "Heshouwushou", "Hi-Commandramon",
                      "Hi-Vision Monitamon", "Holsmon", "Honeybeemon", "Hookmon", "Hover Espimon", "Hudiemon", "Hyougamon", "Ice Devimon", "Icemon", "Igamon", "Ikkakumon",
                      "Jazardmon", "Jungle Mojyamon", "Kabukimon", "Kabuterimon", "Kangarumon", "Karatuki Numemon", "Kaus Gammamon", "Kenkimon", "Kinkakumon", "Kiwimon",
                      "Knight Chessmon (Black)", "Knight Chessmon (White)", "Kokeshimon", "Komondomon", "Kongoumon", "Kougamon", "Kuwagamon", "Kuwagamon (X-Antibody)",
                      "Kyubimon", "Kyubimon (Silver)", "Landramon", "Lavorvomon", "Lekismon", "Leomon", "Leomon (X-Antibody)", "Liamon", "Lianpumon", "Lighdramon",
                      "Liskmon", "Loogarmon", "Lucemon", "Lynxmon", "Löwemon", "Machmon", "Mad Leomon", "Mad Leomon: Armed Mode", "Magnamon", "Magnamon (X-Antibody)",
                      "Mail Birdramon", "Maildramon", "Manbomon", "Manekimon", "Mantaraymon", "Mantaraymon (X-Antibody)", "Marin Devimon", "Master V-dramon", "Mechanorimon",
                      "Meicoomon", "Meramon", "Meramon (X-Antibody)", "Mercuremon", "Mikemon", "Mimicmon", "Minotaurmon", "Mojyamon", "Monitamon", "Monochromon",
                      "Monochromon (X-Antibody)", "Moosemon", "Mori Shellmon", "Mothmon", "Mulemon", "Musyamon", "Namakemon", "Nanimon", "Nefertimon", "Nefertimon (X-Antibody)",
                      "Night Chiropmon", "Nise Drimogemon", "Nohemon", "Numemon", "Numemon (X-Antibody)", "Octmon", "Omega Shoutmon", "Omekamon", "Opossummon", "Orcamon",
                      "Orgemon", "Orgemon (X-Antibody)", "Owlmon", "Paledramon", "Panjyamon", "Parasaurmon", "Peacockmon", "Peckmon", "Pegasmon", "Pegasmon (X-Antibody)",
                      "Petermon", "Pidmon", "Pipismon", "Platinum Scumon", "Ponchomon", "Porcupamon", "Potamon", "Prairiemon", "Pteranomon", "Pteranomon (X-Antibody)",
                      "Publimon", "Pucchiemon", "Pucchiemon (Green)", "Punkmon", "Ranamon", "Rapidmon Armor", "Raptor Sparrowmon", "Raptordramon", "Raremon", "Red V-dramon",
                      "Red Vegimon", "Reppamon", "Revolmon", "Rhamphomon", "Rhinomon", "Rhinomon (X-Antibody)", "Rinkmon", "Rokusho", "Rukamon", "Runnermon", "Saberdramon",
                      "Sagittarimon", "Salamandamon", "Sand Yanmamon", "Sangloupmon", "Scumon", "Seadramon", "Seadramon (X-Antibody)", "Seahomon", "Sealsdramon", "Searchmon",
                      "Sepikmon", "Sethmon", "Shademon", "Shadramon", "Sheepmon", "Shellmon", "Shima Unimon", "Shoeshoemon",
                      "Shonitamon", "Shooting Starmon", "Shortmon", "Shoutmon (King Ver.)", "Shoutmon X2", "Shoutmon X3", "Shoutmon X4", "Shurimon", "Siesamon",
                      "Siesamon (X-Antibody)", "Sistermon Ciel", "Sistermon Ciel (Awake)", "Sistermon Noir", "Sistermon Noir (Awake)", "Skull Knightmon",
                      "Skull Knightmon: Arrow Mode", "Skull Knightmon: Big Axe Mode", "Skull Knightmon: Cavalier Mode", "Skull Knightmon: Naginata Mode", "Snatchmon",
                      "Snimon", "Sorcerimon", "Soulmon", "Starmon", "Starmon (X-Antibody)", "Stegomon", "Stingmon", "Stingmon (Black)", "Strikedramon", "Submarimon",
                      "Sunflowmon", "Swanmon", "Symbare Angoramon", "Tailmon", "Tailmon (X-Antibody)", "Tankmon", "Targetmon", "Tekkamon", "Tenkomon", "Tesla Jellymon",
                      "Thunderballmon", "Thunderballmon (X-Antibody)", "Thunderbirmon", "Tia Ludomon", "Tobiumon", "Tobucatmon", "Tocanmon", "Togemogumon", "Togemon",
                      "Togemon (X-Antibody)", "Tortamon", "Trailmon", "Trailmon Angler", "Trailmon Ball", "Trailmon Buffalo", "Trailmon C-89", "Trailmon Franken",
                      "Trailmon Kettle", "Trailmon Mole", "Trailmon of Darkness", "Trailmon Raccoon Dog", "Trailmon Worm", "Troopmon", "Tuchidarumon", "Turbomon", "Turuiemon",
                      "Tuskmon", "Tuwarmon", "Tylomon", "Tylomon (X-Antibody)", "Tyranomon", "Tyranomon (X-Antibody)", "Tyumon", "Unimon", "V-dramon", "V-dramon (Black)",
                      "Vegimon", "Velgrmon", "Vermillimon", "Vitium Adult", "Vritramon", "Waspmon", "Wendimon", "Wezen Gammamon", "Whamon", "Witchmon", "Wizarmon",
                      "Wizarmon (X-Antibody)", "Wolfmon", "Wolvermon", "Woodmon", "Xiquemon", "XV-mon", "XV-mon (Black)", "Yakiimon", "Yaksamon", "Yanmamon", "Yo!Yo!mon",
                      "Youkomon", "Yukidarumon", "Zassoumon", "Zeke Greymon", "Zubaeagermon", "Shoutmon (Blue)", "Shoutmon Star Sword", "Shoutmon Black", "Shoutmon EX6",
                      "Shoutmon SH", "Shoutmon X2", "Shoutmon X2 Plus M"],

            "Perfect": ["Aegiochusmon", "Aegiochusmon: Blue", "Aegiochusmon: Dark", "Aegiochusmon: Green", "Aegiochusmon: Holy", "Aero V-dramon", "Agnimon", "Ajatarmon",
                        "Aldamon", "Algomon (Perfect)", "Allomon", "Andiramon", "Andiramon (Deva)", "Andromon", "Angewomon", "Angewomon (X-Antibody)", "Anomalocarimon",
                        "Anomalocarimon (X-Antibody)", "Archnemon", "Arkadimon Perfect", "Arkhai Angemon", "Armamon", "Arresterdramon: Superior Mode (Brave Snatcher)",
                        "Assaultmon", "Astamon", "Asuramon", "Atlur Ballistamon", "Atlur Kabuterimon (Blue)", "Atlur Kabuterimon (Red)", "Azhdarmon", "Baalmon",
                        "Baalmon (X-Antibody)", "Bastemon", "Beowolfmon", "Betsumon", "Big Mamemon", "Bishop Chessmon (Black)", "Bishop Chessmon (White)",
                        "Black King Numemon", "Black Mach Gaogamon", "Black Megalo Growmon", "Black Rapidmon", "Blikmon", "Blizzarmon", "Blossomon", "Blue Meramon",
                        "Bolgmon", "Bombermon", "Boutmon", "Brachimon", "Butenmon", "Butterflamon", "Calamaramon", "Cannonbeemon", "Cannonbeemon (Aircraft Carrier)",
                        "Canoweissmon", "Captain Hookmon", "Cardmon R1", "Cardmon R2", "Cargodramon", "Catch Mamemon", "Caturamon", "Cerberumon", "Cerberumon (X-Antibody)",
                      "Cerberumon: Werewolf Mode", "Chaos Grimmon", "Chaperomon", "Chimairamon", "Cho Hakkaimon", "Climbmon", "Crescemon", "Crys Paledramon", "Cyberdramon",
                      "Cyberdramon (2010 Anime Version)", "Cyberdramon (X-Antibody)", "Dagomon", "Daipenmon", "Dark Knightmon", "Dark Superstarmon", "Darumamon", "Death Meramon",
                      "Death-X-DORUguremon", "Decker Greymon", "Delumon", "Destromon", "Diablomon", "Digitamamon", "Dinobeemon", "Divemon", "DORUguremon", "Doumon", "Duramon",
                      "Ebidramon", "Enbarrmon", "Entmon", "Eosmon (Perfect)", "Etemon", "Ex-Tyranomon", "Fantomon", "Fladramon", "Flaremon", "Footmon", "Frozomon", "Fumamon",
                      "Garudamon", "Garudamon (X-Antibody)", "Garummon", "Generamon", "Gerbemon", "Ghilliedhumon", "Gigadramon", "Gigasmon", "Giromon", "Gizmon: XT",
                      "Gogmamon", "Gokuwmon", "Gold V-dramon", "Grademon", "Grademon (Vice)", "Gran Kuwagamon", "Grand Galemon", "Grappu Leomon", "Gravimon", "Great Gryzmon",
                      "Great King Scumon", "Groundramon", "Gusokumon", "Gyukimon", "Hangyomon", "Helloogarmon", "Hippogriffomon", "Hisyaryumon",
                      "Holy Angemon", "Holy Angemon: Priest Mode", "Holydramon", "Hououmon", "Huankunmon", "Imperialdramon: Dragon Mode", "Indaramon", "Infermon", "Insekimon",
                      "Jazarichmon", "Jet Silphymon", "Jewelbeemon","Jokermon", "Jyagamon", "Jyureimon", "Kabukimon", "Kaiser Leomon", "Karakurumon", "Karatenmon",
                      "Kenkimon", "Knightmon", "Kongoumon", "Kumbhiramon", "Kyukimon", "Lady Devimon", "Lady Devimon (X-Antibody)", "Lamiamon", "Lamortmon",
                      "Lavogaritamon", "Lighdramon", "Lilamon", "Lilimon", "Lilimon (X-Antibody)", "Loader Leomon", "Locomon", "Loudmon", "Lucemon: Falldown Mode", "Luminamon",
                      "Lynxmon", "Mach Gaogamon", "Magnamon", "Maildramon", "Majiramon", "Makuramon", "Mamemon", "Mamemon (X-Antibody)", "Mametyramon", "Mammon",
                      "Mammon (X-Antibody)", "Maneuvermon", "Manticoremon", "Marin Angemon", "Marin Bullmon", "Marin Chimairamon", "Marin Devimon", "Master Blimpmon",
                      "Master Tyranomon", "Matadrmon", "Mechanorimon", "Mega Seadramon", "Mega Seadramon (X-Antibody)", "Megadramon", "Megalo Growmon", "Megalo Growmon (Orange)",
                      "Megalo Growmon (X-Antibody)", "Meicrackmon", "Meicrackmon: Vicious Mode", "Mephismon", "Mephismon (X-Antibody)", "Mermaimon", "Mervamon",
                      "Metal Etemon","Metal Fantomon", "Metal Garurumon", "Metal Greymon", "Metal Greymon (2010 Anime Version)", "Metal Greymon (Virus)",
                      "Metal Greymon (Virus) (X-Antibody)", "Metal Greymon (X-Antibody)", "Metal Greymon: \"G\" Erosion Mode", "Metal Greymon: Alterous Mode", "Metal Mamemon",
                      "Metal Mamemon (X-Antibody)", "Metal Seadramon", "Metal Tyranomon", "Metal Tyranomon (X-Antibody)", "Metallife Kuwagamon", "Mihiramon", "Minotaurmon",
                      "Mistymon", "Mockingbirdmon", "Monarch Lizamon", "Monzaemon", "Monzaemon (X-Antibody)", "Mummymon", "Murasamemon", "Muso Knightmon","Nanomon (Digimon)",
                      "Negamon (Evolved Form)", "Neo Devimon", "Oblivimon", "Oboromon", "Okuwamon", "Okuwamon (X-Antibody)", "Oleamon", "Omega Shoutmon", "Omega Shoutmon (X-Antibody)",
                      "Omegamon", "Orochimon", "Owlmon", "Paildramon", "Pajiramon", "Pandamon", "Panjyamon", "Panjyamon (X-Antibody)", "Parrotmon", "Peacockmon", "Petaldramon",
                      "Phelesmon", "Piccolomon", "Piemon", "Pinochimon", "Piranimon", "Pistmon", "Polar Bearmon", "Ponchomon", "Prairiemon", "Proganomon", "Pucchiemon",
                      "Pucchiemon (Green)", "Pumpmon", "Raihimon", "Raiji Ludomon", "Rapidmon Armor", "Rapidmon Perfect", "Raremon", "Rebellimon", "Regulusmon", "Reptilimon",
                      "Rhino Kabuterimon", "Rhinomon", "Rize Greymon", "Rize Greymon (X-Antibody)", "Rook Chessmon (Black)", "Rook Chessmon (White)", "Rosemon", "Saber Leomon",
                      "Sagittarimon", "Sagomon", "Sandiramon", "Sanzomon", "Savior Hackmon", "Scorpiomon", "Scourge Chiropmon", "Seahomon", "Sekkamon",
                      "Sephirothmon", "Shadramon", "Shakkoumon", "Shakomon", "Sharkmon", "Shawujinmon", "Shishimamon", "Shootmon", "Shoutmon DX",
                      "Shoutmon X3GM", "Shoutmon X3SD", "Shoutmon X4B", "Shoutmon X4K", "Shoutmon X4S", "Shoutmon X5", "Shurimon", "Shutumon", "Silphymon", "Sinduramon",
                      "Sirenmon", "Skull Baluchimon", "Skull Greymon", "Skull Greymon: \"G\" Erosion Mode", "Skull Satamon", "Skull Seadramon", "Soloogarmon", "Splashmon",
                      "Splashmon Darkness Mode", "Stiffilmon", "Super Dark Knightmon", "Superstarmon", "Tankdramon", "Taomon", "Taomon (Silver)", "Tekkamon", "Tempomon",
                      "Thetismon", "Tocanmon", "Tonosama Gekomon", "Toropiamon", "Triceramon", "Triceramon (X-Antibody)", "Tyilinmon", "Tylomon", "Vademon", "Vademon (X-Antibody)",
                      "Vajramon", "Valvemon", "Vamdemon", "Vamdemon (X-Antibody)", "Velgrmon", "Venom Vamdemon", "Vermillimon", "Vespamon", "Vikaralamon",
                      "Vikemon", "Volcamon", "Volcdramon", "Vritramon", "Vulturemon", "War Greymon", "Waru Monzaemon", "Waru Seadramon", "Weddinmon", "Were Garurumon",
                      "Were Garurumon (Black)", "Were Garurumon (X-Antibody)","Were Garurumon: Sagittarius Mode", "Whamon Perfect", "Wingdramon", "Wisemon", "Xingtianmon",
                      "Yaeger Dorulumon", "Yatagaramon", "Yatagaramon (2006 Anime Version)", "Yo!Yo!mon", "Zamielmon", "Zanmetsumon", "Zudomon", "Azhdarmon", "Bearcatmon",  ],

            "Ultimate": ["Abbadomon", "Abbadomon Core", "Achillesmon", "Aegisdramon", "Agumon -Yuki no Kizuna-", "Aldamon", "Algomon (Ultimate)", "Alphamon",
                        "Alphamon: Ouryuken", "Amaterasumon", "Amphimon", "Ancient Beatmon", "Ancient Garurumon", "Ancient Greymon", "Ancient Irismon", "Ancient Megatheriumon", 
                        "Ancient Mermaimon", "Ancient Sphinxmon", "Ancient Troiamon", "Ancient Volcamon", "Ancient Wisemon", "Angewomon", "Anubimon", "Apocalymon", "Apollomon",
                         "Apollomon: Whispered", "Arcturusmon", "Ariemon", "Arkadimon Super Ultimate", "Arkadimon Ultimate", "Armagemon", "Armamon", "Armamon: Burst Mode", 
                        "Arresterdramon", "Atratusmon", "Avenge Kidmon", "Babamon", "Bacchusmon", "Bagramon", "Baihumon", "Bancho Golemon", "Bancho Leomon",
                        "Bancho Leomon: Burst Mode", "Bancho Lilimon", "Bancho Mamemon", "Bancho Stingmon", "Barbamon", "Barbamon (X-Antibody)", "Beel Starmon",
                        "Beel Starmon (X-Antibody)", "Beelzebumon", "Beelzebumon (2010 Anime Version)", "Beelzebumon (X-Antibody)", "Beelzebumon: Blast Mode",
                        "Belial Vamdemon", "Belphemon (X-Antibody)", "Belphemon: Rage Mode", "Belphemon: Sleep Mode", "Beowolfmon", "Berserk Titamon", "Big Mamemon",
                        "Big Ukkomon", "Bio Darkdramon", "Bio Lotusmon", "Bio Spinomon", "Black King Numemon", "Black Megalo Growmon", "Black Saint Galgomon",
                        "Black Seraphimon", "Black Seraphimon (DW3)", "Black War Greymon", "Black War Greymon (X-Antibody)", "Blastmon", "Blitz Greymon", "Bloom Lordmon",
                        "Bolgmon", "Boltmon", "Breakdramon", "Brigadramon", "Bryweludramon", "Callismon", "Cannondramon", "Cardmon S1", "Cardmon S2", "Cendrillmon", "Ceresmon",
                        "Ceresmon Medium", "Cernumon", "Chaos Dukemon", "Chaos Dukemon Core", "Chaos Greymon", "Chaos Lord", "Chaos Piemon", "Chaos Seadramon", "Chaosdramon",
                        "Chaosdramon (X-Antibody)", "Chaosmon", "Chaosmon: Valdur Arm", "Cherubimon (Vice)", "Cherubimon (Vice) (X-Antibody)", "Cherubimon (Virtue)",
                        "Cherubimon (Virtue) (X-Antibody)", "Chimairamon", "Chronomon: Destroy Mode", "Chronomon: Destroy Mode (Robot)", "Chronomon: Holy Mode",
                        "Clavis Angemon", "Craniummon", "Craniummon (X-Antibody)", "Cres Garurumon", "Crescemon", "Crossmon", "Cthyllamon", "Daipenmon", "Dalphomon",
                        "Dark Knightmon (X-Antibody)", "Darkdramon", "Darkness Bagramon", "Darkness Bagramon (Dark Knightmon)", "Death-X-DORUgoramon", "Death-X-mon",
                        "Deathmon", "Deathmon (Black)", "Demon", "Demon (X-Antibody)", "Demon Super Ultimate", "Devitamamon", "Diablomon", "Diablomon (X-Antibody)",
                        "Dianamon", "Diarbbitmon", "Dijiangmon", "Dinomon", "Dinorexmon", "Dinotigermon", "Dominimon",  "Done Devimon", "Dorbickmon", "DORUgoramon",
                        "Duftmon", "Duftmon (X-Antibody)", "Duftmon: Leopard Mode", "Dukemon", "Dukemon (X-Antibody)", "Dukemon: Crimson Mode", "Dullahamon", "Durandamon",
                        "Dynasmon", "Dynasmon (X-Antibody)", "EBEmon", "EBEmon (X-Antibody)", "El Doradimon", "Enmamon", "Eosmon (Ultimate)", "Erlangmon",
                        "Erlangmon: Blast Mode", "Ex Maquinamon", "Examon", "Examon (X-Antibody)", "Exo Grimmon", "Fenriloogamon", "Fenriloogamon: Takemikazuchi",
                        "Fros Velgrmon", "Fujinmon", "Gabumon -Yujo no Kizuna-", "Gaiamon", "Gaioumon", "Gaioumon: Itto Mode", "Gallantmon Chaos Mode", "Gankoomon",
                        "Gankoomon (X-Antibody)", "Giant Slayer", "Giga Seadramon", "Gigantic Pumpmon", "Goddramon", "Goddramon (X-Antibody)", "Gokumon", "Gold Numemon (Ultimate)",
                        "Grace Novamon", "Gran Kuwagamon", "Grand Dracumon", "Grand Locomon", "Grandis Kuwagamon", "Grey Knightsmon", "Griffomon", "Griffomon", "Gulfmon",
                        "Gundramon", "Habakirimon", "Heavy Leomon", "Heavy Metaldramon", "Herakle Kabuterimon", "Herakle Kabuterimon (X-Antibody)", "Hermmon", "Hexeblaumon",
                        "Hi Andromon", "Holy Digitamamon", "Holydramon", "Holydramon (X-Antibody)", "Hououmon", "Hououmon (X-Antibody)", "Huanglongmon", "Huanglongmon: Ruin Mode",
                        "Hydramon", "Imperialdramon: Dragon Mode", "Imperialdramon: Dragon Mode (Black)", "Imperialdramon: Fighter Mode", "Imperialdramon: Fighter Mode (Black)",
                        "Imperialdramon: Paladin Mode", "Invisimon", "JESmon", "JESmon (X-Antibody)", "JESmon GX", "Jet Mervamon", "Jet Silphymon", "Jijimon", "Jokermon",
                        "Jougamon", "Jumbo Gamemon", "Junomon", "Junomon: Hysteric Mode", "Jupitermon", "Jupitermon: Wrath Mode",  "Justimon (X-Antibody)", "Justimon: Accel Arm",
                        "Justimon: Blitz Arm", "Justimon: Critical Arm", "Jyureimon (Christmas Tree)", "Kaguyamon", "Kaiser Greymon", "Kazuchimon", "King Chessmon", "King Etemon",
                        "King Whamon", "Kuzuhamon", "Kuzuhamon: Miko Mode", "Laeus Greymon", "Lampmon", "Leviamon", "Leviamon (X-Antibody)", "Lilithmon", "Lilithmon (X-Antibody)",
                        "Lord Knightmon", "Lord Knightmon (X-Antibody)", "Lotusmon", "Lovely Angemon", "Lucemon (X-Antibody)", "Lucemon: Falldown Mode", "Lucemon: Larva",
                        "Lucemon: Satan Mode", "Lykamon", "Magna Garurumon", "Magna Kidmon", "Magnamon", "Magnamon (X-Antibody)", "Magneticdramon", "Marin Angemon",
                        "Marin Devimon", "Marsmon", "Mastemon", "Master", "Medieval Dukemon", "Medusamon", "Megidramon", "Megidramon (X-Antibody)", "Mercurymon", "Mervamon",
                        "Metal Etemon", "Metal Garurumon", "Metal Garurumon (Black)", "Metal Garurumon (X-Antibody)", "Metal Piranimon", "Metal Seadramon", "Metallicdramon",
                        "Metamormon", "Metatromon", "Millenniumon", "Minervamon", "Minervamon (X-Antibody)", "Mirage Gaogamon", "Mirage Gaogamon: Burst Mode", "Mitamamon",
                        "Miyuki (Kenzoku)", "Moon Millenniumon", "Mugendramon", "Mugendramon: MFS-3 Mode", "Murmukusmon", "Necromon", "Neo Vamdemon",
                        "Neo Vamdemon Darkness Mode (Metal Greymon)", "Neo Vamdemon Darkness Mode (Vampire Army)", "Neptunemon", "Nezhamon", "Nezhamon: Crimson Mode",
                        "Nidhoggmon", "Noble Pumpmon", "Nyabootmon", "Ofanimon", "Ofanimon (X-Antibody)", "Ofanimon Core", "Ofanimon: Falldown Mode",
                        "Ofanimon: Falldown Mode (X-Antibody)", "Ogudomon", "Ogudomon (X-Antibody)", "Olegmon", "Omedamon", "Omega Shoutmon", "Omegamon",
                        "Omegamon (X-Antibody)", "Omegamon Alter-B", "Omegamon Alter-S", "Omegamon Zwart", "Omegamon Zwart Defeat", "Omegamon: \"G\" Fusion Mode",
                        "Omegamon: Merciful Mode", "Ordinemon", "Ornismon", "Ouryumon", "Overlord GAIA", "Panimon", "Parallelmon", "Parasimon", "Pharaohmon", "Piemon",
                        "Pile Volcamon", "Pinochimon", "Platinum Numemon", "Plesiomon", "Plesiomon (X-Antibody)", "Plutomon", "Plutomon (Fusion)", "Prince Mamemon",
                        "Prince Mamemon (X-Antibody)", "Proximamon", "Pukumon", "Pyramidimon", "Qinglongmon", "Quantumon", "Quartzmon", "Queenbeemon", "Rafflesimon",
                        "Ragna Lordmon", "Ragnamon", "Raguelmon", "Raidenmon", "Raihimon", "Raijinmon", "Rapidmon (X-Antibody)", "Rapidmon Armor", "Rasenmon",
                        "Rasenmon: Fury Mode", "Rasielmon", "Ravmon", "Ravmon: Burst Mode", "Reaper", "Regalecusmon", "Regulumon", "Rosemon", "Rosemon (X-Antibody)",
                        "Rosemon: Burst Mode", "Rubeusdramon", "Rust Tyranomon", "Ryugumon", "Saber Leomon", "Saint Galgomon", "Sakuyamon", "Sakuyamon (X-Antibody)",
                        "Sakuyamon: Miko Mode", "Seiten Gokuwmon", "Seraphimon", "Shagaramon", "Shakamon", "Shin Monzaemon", "Shine Greymon", "Shine Greymon: Burst Mode",
                        "Shine Greymon: Ruin Mode", "Shivamon", "Shoutmon DX", "Shoutmon EX6", "Shoutmon X5B", "Shoutmon X5S", "Shoutmon X7", "Shoutmon X7: Superior Mode",
                        "Shroudmon", "Siriusmon", "Skadimon", "Skull Knightmon", "Skull Knightmon: Cavalier Mode", "Skull Mammon", "Skull Mammon (X-Antibody)",
                        "Skull Satamon", "Slash Angemon", "Slayerdramon", "Sleipmon", "Sleipmon (X-Antibody)", "Sleipmon: Burst Mode", "Spinomon", "Styracomon",
                        "Suijinmon", "Superstarmon", "Surfimon", "Susanoomon", "Tactimon", "Takutoumon", "Takutoumon: Wrath Mode", "Taotiemon", "Taowumon", "Technodramon",
                        "Tengumon", "Tiger Vespamon", "Titamon", "Titamon + Skull Baluchimon", "Tlalocmon", "Tonosama Mamemon", "Tyrant Kabuterimon", "Ulforce V-dramon",
                        "Ulforce V-dramon (X-Antibody)", "Ulforce V-dramon Future Mode", "Ultimate Brachimon", "Ultimate Chaosmon", "Valdurmon", "Valkyrimon", "Venom Vamdemon",
                        "Venusmon", "Victory Greymon", "Vikemon", "Vitium Ultimate", "Volcanicdramon", "Voltobautamon", "Voltobautamon (Fusion)", "Vortexdramon", "Vulcanusmon",
                        "War Greymon", "War Greymon (X-Antibody)", "War Greymon: \"G\" Erosion Mode", "Xiangpengmon", "Xros Up Mervamon (Beelzebumon)", "Xuanwumon", "Yihumon",
                        "Yukinamon", "Z'd Garurumon", "Zanbamon", "Zeed Millenniumon", "Zeke Greymon", "Zephagamon", "Zhuqiaomon", "Zino Garurumon", "Zombie Plutomon"]

        },
        "reglas": {
            "Baby I": { "1": ["Baby"], "2": ["Baby"], "3": ["Baby"], "4": ["Baby"], "5": ["Baby"], "6": ["Baby"], "7": ["Baby", "Child"], "8": ["Baby", "Child"] },
            "Baby II": {  "1": ["Baby"], "2": ["Baby"], "3": ["Baby"], "4": ["Baby"], "5": ["Baby"], "6": ["Baby"], "7": ["Baby"], "8": ["Baby"] },

            "Child": { "1": ["Child"], "2": ["Child", "Adult"], "3": ["Child", "Adult"], "4": ["Child", "Adult", "Perfect", "Ultimate"],
            "5": ["Child", "Adult"], "6": ["Child", "Adult"], "7": ["Child", "Adult", "Perfect", "Ultimate"], "8": ["Child", "Adult"] },

            "Adult": { "1": ["Adult"], "2": ["Adult", "Perfect"], "3": ["Adult", "Perfect"], "4": ["Child", "Adult", "Perfect", "Ultimate"], 
            "5": ["Adult", "Perfect"], "6": ["Adult", "Perfect"], "7": ["Child", "Adult", "Perfect", "Ultimate"], "8": ["Adult", "Perfect"] },

            "Perfect": { "1": ["Perfect"], "2": ["Adult", "Perfect", "Ultimate" ], "3": ["Adult", "Perfect"], "4": ["Child", "Adult", "Perfect", "Ultimate"],
            "5": ["Adult", "Perfect"], "6": ["Adult", "Perfect"], "7": ["Child", "Adult", "Perfect", "Ultimate"], "8": ["Adult", "Perfect"] },

            "Ultimate": { "1": ["Ultimate"], "2": ["Perfect", "Ultimate" ], "3": ["Perfect", "Ultimate"], "4": ["Child", "Adult", "Perfect", "Ultimate"],
            "5": ["Perfect","Ultimate"], "6": ["Perfect","Ultimate"], "7": ["Child", "Adult", "Perfect", "Ultimate"], "8": ["Adult", "Perfect","Ultimate"] }
        }
    }
};

const etiquetasVisuales = {
    "digitama": ["Cáscara", "Patrones", "Color patrón", "Extra 1", "Extra 2"], 
    "digimon": ["Etapa", "Base", "Cabeza", "Mandibula", "Cola", "Extremidades", "Piel", "Colores", "Extra"],
};


const descripcionesCategorias = {
    "digitama_set": "Dibuja el huevo de tu digimon.",
    "digimon_set": "Dibuja tu monstruo digital.",
    "Cáscara": "Color general del Digitama",
    "Base": "Cuerpo, vestimenta y forma general.",
    "Patrones": "Diseños o marcas de textura sobre la superficie.",
    "Color patrón": "Colores del patrón.",
    "Extra 1": "Detalles extras a agregar.",
    "Extra 2": "Detalles extras a para que sufras.",
    "Etapa": "Estadio evolutivo.",
    "Cabeza": "Forma del craneo, orejas, ojos y tal vez accesorios",
    "Mandibula": "Forma general de la nariz, hocico, boca y/o pinzas (si es que tiene).",
    "Cola": "Protuberancia, turbina, cola, hélice o lo que toque.",
    "Extremidades": "Brazos, piernas, patas, alas, tentáculos, ¿Ruedas?",
    "Piel": "Textura (metálico, con pelaje, escamas, placas, etc.).",
    "Colores": "Distribución de los colores.",
    "Extra": "Ropa, armadura, marcas y/o incrustaciones en piel, etc..."
};
